[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

# Production context
[context.production]
  environment = { NODE_ENV = "production" }

# Deploy Preview context
[context.deploy-preview]
  environment = { NODE_ENV = "production" }

# Branch Deploy context
[context.branch-deploy]
  environment = { NODE_ENV = "production" }

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy (if needed)
[[redirects]]
  from = "/api/*"
  to = "https://your-api.com/api/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify" }

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = """
      default-src 'self' https:; 
      script-src 'self' 'unsafe-inline' 'unsafe-eval'; 
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; 
      img-src 'self' data: https: blob:; 
      font-src 'self' data: https://fonts.gstatic.com;
      connect-src 'self' https: wss:;
      frame-ancestors 'none';
      form-action 'self';
      base-uri 'self';
      """